/*
Brian Hodge
C00170400
CMPS 260
Programming Assignment: #8
Due Date: 05/01/2019 @11:45pm
Program Description:
The program reads in strings from a file, stores the lines of strings into an ArrayList.
The java.util.Collections.sort() method is called to sort the list, then create a new file and output the
sorted list of books and authors in the new file using PrintWriter.
Certificate of Authenticity:
I certify that the code of this project, other than that that was generated by IntelliJ, is entirely my own work.

 */

package com.company;

import java.util.*;
import java.io.*;

public class Main {

    public static void main(String[] args) {
    File inputFile = new File("oldbooks.txt");
    try (Scanner reader = new Scanner(inputFile)) {
        ArrayList<Book> books = new ArrayList<>();
        while (reader.hasNext()) {
            int a = 0;
            int b = 1;
            String s1 = reader.nextLine();
            String[] split = s1.split(",");
            Book nameOfBook = new Book(split[a], split[b]);
            books.add(nameOfBook);
        }
        Collections.sort(books);
        try(PrintWriter output = new PrintWriter("outputFile.txt")) {
            for (int i = 0; i < books.size(); i++) {
                output.println(books.get(i).getTitle() + "," + books.get(i).getAuthor());
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            System.exit(0);
        }
    } catch (Exception ex) {
        ex.printStackTrace();
    }

    }

}